Hadouken/src/main/Java/br/com/hadouken/entity/TipoProduto.java
package br.com.hadouken.entity;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 *
 * @author u0181089
 */
@Entity
@Table(name = "tipoproduto")
public class TipoProduto implements PersistentEntity<Long>, Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String nome;
    @NotNull
    private Boolean ativo;
    @ManyToOne
    @NotNull
    private Usuario usuarioCadastro;


    public TipoProduto() {
        ativo = true;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Usuario getUsuarioCadastro() {
        return usuarioCadastro;
    }

    public void setUsuarioCadastro(Usuario usuarioCadastro) {
        this.usuarioCadastro = usuarioCadastro;
    }
    
    public Boolean getAtivo() {
        return ativo;
    }

    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }

    @Override
    public boolean isNew() {
        return this.id == null;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TipoProduto other = (TipoProduto) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

}

Hadouken/src/main/webapp/webpage/configuracao/cadastro/tipoproduto/incluirEditar.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition template="/resources/template/common/lateralbar/lateralBarLayout.xhtml"> 
            <ui:define name="lateralBar">
                <ui:insert name="cadastroLateralBar">
                    <ui:include src="../cadastroLateralBar.xhtml"/>
                </ui:insert>
            </ui:define>
            <ui:define name="contentLateralBar">
                <h:form id="formularioCadastro">
                    <h:outputLabel value="Inclusão e edição de tipos de produtos" styleClass="contentTitle" />
                    <br/>
                    <p:commandButton value="Voltar" immediate="true" action="#{tipoProdutoView.voltar()}"/>
                    <p:commandButton value="Novo" action="#{tipoProdutoView.novo()}"/>
                    <p:commandButton value="Salvar" update="@form" actionListener="#{tipoProdutoView.salvar()}"/>
                    <p:commandButton value="Cancelar alterações" update="@form" immediate="true" action="#{tipoProdutoView.cancelarAlteracoes()}"/>
                    <br/>
                    <p:messages showDetail="true"/>
                    <h:panelGrid id="formularioCadastroGrid"
                                 columns="2"
                                 styleClass="formularioCadastroGrid">
                        
                        <p:outputLabel styleClass="labelFormularioCadastro" value="Nome:" for="nome"/>
                        <p:inputText id="nome" required="true" value="#{tipoProdutoView.tipoProduto.nome}"/>
                                                
                        <p:outputLabel styleClass="labelFormularioCadastro" value="Ativo" for="ativo"/>
                        <p:selectBooleanCheckbox id="ativo" required="true" disabled="#{tipoProdutoView.tipoProduto.new}" value="#{tipoProdutoView.tipoProduto.ativo}"/>
                                                
                    </h:panelGrid>
                </h:form>
            </ui:define>
        </ui:composition> 
    </h:body>
</html>

Hadouken/src/main/webapp/webpage/configuracao/cadastro/tipoproduto/listar.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition template="/resources/template/common/lateralbar/lateralBarLayout.xhtml"> 
            <ui:define name="lateralBar">
                <ui:insert name="cadastroLateralBar">
                    <ui:include src="../cadastroLateralBar.xhtml"/>
                </ui:insert>
            </ui:define>
            <ui:define name="contentLateralBar">
                <h:form id="formListar">
                    <h:outputLabel value="Tipos de produto" styleClass="contentTitle" />
                    <br/>
                    <p:commandButton value="Novo" ajax="false" action="#{tipoProdutoView.novo()}" />
                    <p:commandButton id="botaoEditar" value="Editar" ajax="false" disabled="#{tipoProdutoView.tipoProduto.new}" action="#{tipoProdutoView.editar()}"/>
                    <p:dataTable var="tipoProduto"
                                 selectionMode="single"
                                 emptyMessage="Nenhum registro encontrado."
                                 selection="#{tipoProdutoView.tipoProduto}"
                                 value="#{tipoProdutoView.tiposProduto}"
                                 rowKey="#{tipoProduto}">
                            <p:ajax event="rowSelect"
                                    update=":formListar:botaoEditar" />
                            <p:ajax event="rowUnselect"
                                    update=":formListar:botaoEditar" />
                        <p:column> 
                            <f:facet name="header">
                                <h:outputText value="Nome" styleClass="columnTitleDatatable"/>  
                            </f:facet> 
                            <h:outputText value="#{tipoProduto.nome}" />
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Ativo" styleClass="columnTitleDatatable"/>  
                            </f:facet> 
                            <h:outputText value="#{tipoProduto.ativo ? 'Sim' : 'Não'}" />
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>
        </ui:composition> 
    </h:body>
</html>